/**
 * cv-review.mjs — the headless equivalent of modes/pdf.md step 14a.
 *
 * Step 14a tells the agent to stop and ask before putting anything on the CV
 * that cv.md does not support. That works when a human is in the conversation.
 * Web and extension runs go through spawnHeadlessCli, which gives the agent no
 * channel to receive an answer on — so on those surfaces the run stops before
 * rendering, the findings reach the UI, and /api/cv-review resumes it.
 *
 * Thin on purpose. The rule for what counts as unsupported lives in the core's
 * verify-cv-facts.mjs and is shared with the CLI path; duplicating it here would
 * give the two surfaces two different answers to the same question.
 *
 * Plain .mjs (same pattern as cv-envelope.mjs / pdf-paths.mjs) so it is
 * unit-testable with `node --test`, no TypeScript build step.
 */
import path from "node:path";
import { pathToFileURL } from "node:url";

/**
 * Load the core's fact verifier and return a SYNCHRONOUS competency checker.
 *
 * Awaited once before the response stream opens, deliberately. The call site is
 * inside child.on("close"), a sync handler: making that async to await an import
 * would turn any throw into an unhandled rejection on a path whose entire job is
 * to guarantee the stream ends with either an error or a done event.
 *
 * Resolved through the core at runtime rather than imported at module load —
 * CAREER_OPS_ROOT can point at a data-only checkout with no scripts, and a
 * top-level import would take the whole route down with it. A review step that
 * cannot run degrades to "nothing to ask about", never to a 500: the CV is
 * already generated by then, and losing work the user paid tokens for is worse
 * than skipping a check.
 *
 * @param {string} root - careerOpsRoot().
 * @returns {Promise<(html: string) => string[]>}
 */
export async function loadCompetencyChecker(root) {
  let verifyFacts;
  try {
    ({ verifyFacts } = await import(pathToFileURL(path.join(root, "verify-cv-facts.mjs")).href));
  } catch {
    return () => [];
  }
  return (html) => {
    if (!html) return [];
    try {
      const result = verifyFacts(html, { cwd: root });
      return Array.isArray(result?.unsupportedCompetencies) ? result.unsupportedCompetencies : [];
    } catch {
      // A malformed cv-facts.json or unreadable cv.md must not strand a
      // finished CV — same reasoning as the import guard above.
      return [];
    }
  };
}
